version: "3.7"

services:
  database:
    image: postgres:11
    ports:
      - 5433:5432
    volumes:
      - postgres-orders:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders

volumes:
  postgres-orders: